### ISSUE TITLE
MIToS benchmarks

### ISSUE THREAD

**Issue by diegozea** [jgreener64/pdb-benchmarks#1]
Could I add [MIToS.PDB](https://github.com/diegozea/MIToS.jl) benchmarks to this repo? Thanks!

**Comment by jgreener64** [comment]
Yes of course! I put some brief contributing notes in the README. Thanks.

**Comment by diegozea** [comment]
Thanks! I did the PR (https://github.com/jgreener64/pdb-benchmarks/pull/2), so I'm closing this issue.
