### ISSUE TITLE
update MDA benchmarks

### ISSUE THREAD

**Issue by richardjgowers** [jgreener64/pdb-benchmarks#4]
Hi @jgreener64, we just released 0.18.0 of MDAnalysis and hopefully there's some performance improvements.  I checked the scripts and they should all work the same, so could we get them rerun?

**Comment by jgreener64** [comment]
Thanks for the info. I will look to re-run these but it might take a while to set up as I will have to install everything on a new computer after a lab switch...

Meanwhile I will put a note on the readme saying that some packages may be out of date (I know a couple of the others are too).

**Comment by jgreener64** [comment]
All updated now, thanks.
